# Módulo 1 Ejercicios de Python
### Fundamentos de NumPy y Pandas

**Autor:** Camilo Romero

---

Este notebook presenta la solución de los **Ejercicios 1, 2 y 3** del módulo, con explicaciones,
código comentado y visualización de resultados tras cada bloque de ejecución.

**Contenido:**
1. [Ejercicio 1 — Factorial y comparación de vectores](#Ejercicio-1)
2. [Ejercicio 2 — Matrices aleatorias y transformación condicional](#Ejercicio-2)
3. [Ejercicio 3 — Análisis exploratorio de datos con Pandas](#Ejercicio-3)

**Librerías utilizadas:** `numpy`, `pandas`


In [1]:
import numpy as np
import pandas as pd

# Semilla fija para que los resultados aleatorios sean reproducibles
np.random.seed(42)

# Configuración de presentación de Pandas
pd.set_option('display.precision', 2)

print('Entorno listo: NumPy', np.__version__, '| Pandas', pd.__version__)

Entorno listo: NumPy 2.4.4 | Pandas 3.0.2


---
## Ejercicio 1

Dado un valor `n`:

1. Calcular el factorial mediante una función.
2. Crear dos vectores aleatorios `V1` y `V2` de tamaño `n`, con valores entre 1 y 10.
3. Crear `V3`, donde `V3[i] = 0` si `V1[i] < V2[i]` y `1` en caso contrario.
4. Concatenar los tres vectores como columnas para obtener una matriz `n x 3`.


In [2]:
# Valor de n
n = 10

# Función para calcular el factorial
def factorial(n):
    resultado = 1
    for i in range(1, n + 1):
        resultado *= i
    return resultado

# Calcular factorial
resultado = factorial(n)
print(f'El factorial de {n} es: {resultado}')

El factorial de 10 es: 3628800


In [3]:
# Crear vectores aleatorios entre 1 y 10
V1 = np.random.randint(1, 11, n)
V2 = np.random.randint(1, 11, n)

# Crear V3 según la comparación
V3 = np.where(V1 < V2, 0, 1)

print('V1:', V1)
print('V2:', V2)
print('V3:', V3)

V1: [ 7  4  8  5  7 10  3  7  8  5]
V2: [4 8 8 3 6 5 2 8 6 2]
V3: [1 0 1 1 1 1 1 0 1 1]


In [4]:
# Convertir los vectores en columnas y concatenarlos en una matriz n x 3
matriz = np.concatenate((
    V1.reshape(-1, 1),
    V2.reshape(-1, 1),
    V3.reshape(-1, 1)
), axis=1)

df_matriz = pd.DataFrame(matriz, columns=['V1', 'V2', 'V3 (V1<V2 -> 0, si no 1)'])
df_matriz

,V1,V2,"V3 (V1<V2 -> 0, si no 1)"
0,7,4,1
1,4,8,0
2,8,8,1
3,5,3,1
4,7,6,1
5,10,5,1
6,3,2,1
7,7,8,0
8,8,6,1
9,5,2,1


**Resultado:** la matriz `n x 3` resume, fila a fila, los valores de `V1`, `V2` y la
comparación booleana codificada en `V3`. Puede verificarse visualmente que `V3` vale `0`
únicamente cuando `V1 < V2`.

---
## Ejercicio 2

Dados `m` (número de filas) y `n` (número de columnas):

1. Crear una matriz `A` de dimensiones `m x n` inicializada con ceros.
2. Recorrer las columnas usando `while` y llenarlas con números aleatorios enteros entre `-1` y `3`.
3. Usar dos bucles `while` para reemplazar los valores negativos por `-1` y los no negativos por `5`.
4. Repetir la transformación usando dos bucles `for` y comprobar que ambos resultados son iguales.


In [5]:
# Valores de m y n
m = 4
n = 3

# 1. Crear matriz de ceros
A = np.zeros((m, n), dtype=int)
print('Matriz inicial:')
print(A)

Matriz inicial:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
# 2. Llenar la matriz usando while
j = 0
while j < n:
    A[:, j] = np.random.randint(-1, 4, m)
    j += 1

print('Matriz con números aleatorios:')
print(A)

Matriz con números aleatorios:
[[ 2  0 -1]
 [ 3  3  1]
 [-1  2  1]
 [ 2 -1  0]]


In [7]:
# 3. Transformar usando dos bucles while
A_while = A.copy()
i = 0
while i < m:
    j = 0
    while j < n:
        if A_while[i, j] < 0:
            A_while[i, j] = -1
        else:
            A_while[i, j] = 5
        j += 1
    i += 1

print('Matriz transformada usando while:')
print(A_while)

Matriz transformada usando while:
[[ 5  5 -1]
 [ 5  5  5]
 [-1  5  5]
 [ 5 -1  5]]


In [8]:
# 4. Repetir la transformación usando dos bucles for
A_for = A.copy()
for i in range(m):
    for j in range(n):
        if A_for[i, j] < 0:
            A_for[i, j] = -1
        else:
            A_for[i, j] = 5

print('Matriz transformada usando for:')
print(A_for)

# Comparar resultados
son_iguales = np.array_equal(A_while, A_for)
print('\n¿Las matrices finales son iguales?', son_iguales)

Matriz transformada usando for:
[[ 5  5 -1]
 [ 5  5  5]
 [-1  5  5]
 [ 5 -1  5]]

¿Las matrices finales son iguales? True


In [9]:
# Visualización comparativa lado a lado
comparacion = pd.concat(
    [pd.DataFrame(A, columns=[f'col{j}' for j in range(n)]).add_prefix('orig_'),
     pd.DataFrame(A_while, columns=[f'col{j}' for j in range(n)]).add_prefix('while_'),
     pd.DataFrame(A_for, columns=[f'col{j}' for j in range(n)]).add_prefix('for_')],
    axis=1
)
comparacion

,orig_col0,orig_col1,orig_col2,while_col0,while_col1,while_col2,for_col0,for_col1,for_col2
0,2,0,-1,5,5,-1,5,5,-1
1,3,3,1,5,5,5,5,5,5
2,-1,2,1,-1,5,5,-1,5,5
3,2,-1,0,5,-1,5,5,-1,5


**Resultado:** la tabla comparativa muestra, para cada celda de la matriz original,
el valor obtenido con el enfoque `while` y con el enfoque `for`. Ambos métodos producen
matrices idénticas, lo que confirma que la lógica de transformación es correcta
independientemente de la estructura de control utilizada.

---
## Ejercicio 3

Se recolectaron datos de 8 estudiantes universitarios con las variables:
`MASA`, `ESTATURA`, `GENERO`, `ESTRATO` y `FUMA`.

Se solicita:

1. Crear un DataFrame llamado `df`.
2. Realizar un análisis descriptivo básico de todas las variables.
3. Extraer los primeros 4 estudiantes y guardarlos en `subc1`.
4. Extraer las variables categóricas y guardarlas en `subc2`.
5. Extraer las variables numéricas y guardarlas en `subc3`.


In [10]:
# Datos de los 8 estudiantes
data = {
    'MASA': [71, 45, 50, 60, 61, 84, 55, 60],
    'ESTATURA': [183, 168, 164, 164, 167, 182, 168, 170],
    'GENERO': ['HOMBRE', 'HOMBRE', 'HOMBRE', 'MUJER',
               'HOMBRE', 'HOMBRE', 'MUJER', 'HOMBRE'],
    'ESTRATO': [2, 1, 1, 3, 3, 3, 3, 3],
    'FUMA': ['NO', 'NO', 'NO', 'SI', 'SI', 'NO', 'NO', 'SI']
}

# 1. Crear el DataFrame
df = pd.DataFrame(data)
df

,MASA,ESTATURA,GENERO,ESTRATO,FUMA
0,71,183,HOMBRE,2,NO
1,45,168,HOMBRE,1,NO
2,50,164,HOMBRE,1,NO
3,60,164,MUJER,3,SI
4,61,167,HOMBRE,3,SI
5,84,182,HOMBRE,3,NO
6,55,168,MUJER,3,NO
7,60,170,HOMBRE,3,SI


In [11]:
# 2. Análisis descriptivo básico de todas las variables
df.describe(include='all')

,MASA,ESTATURA,GENERO,ESTRATO,FUMA
count,8.00,8.00,8,8.00,8
unique,NaN,NaN,2,NaN,2
top,NaN,NaN,HOMBRE,NaN,NO
freq,NaN,NaN,6,NaN,5
mean,60.75,170.75,NaN,2.38,NaN
std,12.21,7.54,NaN,0.92,NaN
min,45.00,164.00,NaN,1.00,NaN
25%,53.75,166.25,NaN,1.75,NaN
50%,60.00,168.00,NaN,3.00,NaN
75%,63.50,173.00,NaN,3.00,NaN


In [12]:
# Información general del DataFrame
df.info()
print('\nDimensiones del DataFrame (filas, columnas):', df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MASA      8 non-null      int64
 1   ESTATURA  8 non-null      int64
 2   GENERO    8 non-null      str  
 3   ESTRATO   8 non-null      int64
 4   FUMA      8 non-null      str  
dtypes: int64(3), str(2)
memory usage: 452.0 bytes

Dimensiones del DataFrame (filas, columnas): (8, 5)


In [13]:
# 3. Primeros 4 estudiantes
subc1 = df.iloc[:4]
subc1

,MASA,ESTATURA,GENERO,ESTRATO,FUMA
0,71,183,HOMBRE,2,NO
1,45,168,HOMBRE,1,NO
2,50,164,HOMBRE,1,NO
3,60,164,MUJER,3,SI


In [14]:
# 4. Variables categóricas
subc2 = df[['GENERO', 'FUMA']]
subc2

,GENERO,FUMA
0,HOMBRE,NO
1,HOMBRE,NO
2,HOMBRE,NO
3,MUJER,SI
4,HOMBRE,SI
5,HOMBRE,NO
6,MUJER,NO
7,HOMBRE,SI


In [15]:
# 5. Variables numéricas
subc3 = df[['MASA', 'ESTATURA', 'ESTRATO']]
subc3

,MASA,ESTATURA,ESTRATO
0,71,183,2
1,45,168,1
2,50,164,1
3,60,164,3
4,61,167,3
5,84,182,3
6,55,168,3
7,60,170,3


In [16]:
# Visualización adicional: distribución de género y hábito de fumar
resumen_genero = df['GENERO'].value_counts()
resumen_fuma = df['FUMA'].value_counts()

print('Distribución por GÉNERO:')
print(resumen_genero)
print('\nDistribución por FUMA:')
print(resumen_fuma)

Distribución por GÉNERO:
GENERO
HOMBRE    6
MUJER     2
Name: count, dtype: int64

Distribución por FUMA:
FUMA
NO    5
SI    3
Name: count, dtype: int64


**Resultado:** el análisis descriptivo (`describe`) resume media, desviación estándar y
cuartiles de las variables numéricas, y frecuencias/moda de las categóricas. Los subconjuntos
`subc1`, `subc2` y `subc3` confirman que la selección por filas y por tipo de columna se
realizó correctamente.

---
## Conclusiones

- **Ejercicio 1** mostró el uso de NumPy para generar vectores aleatorios, aplicar comparaciones
  vectorizadas (`np.where`) y ensamblar los resultados en una matriz mediante `concatenate`.
- **Ejercicio 2** comparó dos formas de recorrer y transformar una matriz (`while` vs `for`),
  verificando que ambos enfoques son equivalentes en resultado, aunque difieren en estilo.
- **Ejercicio 3** aplicó Pandas para construir un DataFrame, generar estadística descriptiva y
  segmentar los datos por filas y por tipo de variable (categórica vs. numérica).

*Fin de los ejercicios del Módulo 1.*
